aspirantes/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from usuarios.views import LoginView,LogoutView
from app.views import Home
from personas.views import Personas
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/', TemplateView.as_view(template_name="index.html")),
    url(r'', include('vacantes.urls')),
    url(r'', include('solicitudes.urls')),
    url(r'', include('contratos.urls')),
    url(r'^aspirantes/', Personas.as_view()),
    url(r'^login/$', LoginView.as_view(), name='Login'),
    url(r'^$', Home.as_view()),
    url(r'^salir/$', LogoutView.as_view(),name='Salir'),
    #url(r'^salir/$', 'django.contrib.auth.views.logout',{'next_page': '/login/'},name='Salir'),
    #url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
    #        'document_root': settings.STATIC_ROOT,
    #}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vacantes/urls.py
from django.conf.urls import patterns, url
from .views import Vacantes,VacanteCreate,VacanteUpdate,VacanteDelete
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^vacantes/$', login_required(Vacantes.as_view()), name='vacantes'),
	#url(r'^albums/(?P<titulo>[\w\-]+)/$', login_required(AlbumListView.as_view()), name='albums'),
	url(r'^vacante/$', login_required(VacanteCreate.as_view()), name='vacante'),
	url(r'^vacante_edit/(?P<pk>\d+)$', login_required(VacanteUpdate.as_view()), name='vacante_edit'),
	url(r'^vacante_delete/(?P<pk>\d+)$', login_required(VacanteDelete.as_view()), name='vacante_delete'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Escolaridad(models.Model):
    escolaridad=models.CharField(max_length=100)
    def __unicode__(self):
        return self.escolaridad

class Tag(models.Model):
    tag=models.CharField(max_length=100)
    def __unicode__(self):
        return self.tag
'''
class Aspirante(models.Model):
    correo=models.EmailField()
    nombre=models.CharField(max_length=255)
    direccion=models.TextField()
    telefono=models.CharField(max_length=100)
    curriculum=models.FileField(upload_to='curriculums')
    ciudad=models.CharField(max_length=100)
    calificacion=models.CharField(max_length=3)
    Escolaridad=models.ForeignKey(Escolaridad)
    def __unicode__(self):
        return self.correo

class AspiranteTags(models.Model):
    Aspirante=models.ForeignKey(Aspirante)
    Tag=models.ForeignKey(Tag)

class Solicitud(models.Model):
    Aspirante=models.ForeignKey(Aspirante)
    Vacante=models.ForeignKey(Vacante)
    fecha=models.DateTimeField(auto_now_add=True,editable=False)
    usuario=models.ForeignKey(User)

class Contratos(models.Model):
    Vacante=models.ForeignKey(Vacante)
    Solicitud=models.ForeignKey(Solicitud)
    fecha=models.DateTimeField(auto_now_add=True,editable=False)
    usuario=models.ForeignKey(User)
'''

vacantes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Vacante(models.Model):
    titulo=models.CharField(max_length=255)
    descripcion=models.TextField()
    fecha=models.DateTimeField(auto_now_add=True,editable=False)
    estado=models.BooleanField(default=False)
    usuario=models.ForeignKey('auth.User',editable=False)

    def __unicode__(self):
        return self.titulo

vacantes/forms.py
from django import forms
from .models import Vacante
from django.forms import Textarea

class VacanteForm(forms.ModelForm):
    class Meta:
        model = Vacante
        fields = "__all__"
        widgets={
            "titulo":forms.TextInput(attrs={'placeholder':'Escriba el titulo','required':'True','class':'form-control fg-input'}),
            "descripcion":forms.Textarea(attrs={'placeholder':'Escriba la descripcion del empleo','required':'True','rows':'5','class':'form-control'}),
        }

vacantes/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.views.generic import ListView
from .forms import VacanteForm
from .models import Vacante
from contratos.models import Contrato
from django.http import JsonResponse

# Create your views here.

class Vacantes(ListView):
	template_name = "vacantes.html"
	model = Vacante
	context_object_name = "vacantes"

	def dispatch(self, *args, **kwargs):
		return super(Vacantes, self).dispatch(*args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(Vacantes, self).get_context_data(**kwargs)
		return context

	def get_queryset(self):
		contratos=Contrato.objects.all()
		queryset=super(Vacantes,self).get_queryset().exclude(contrato__in=contratos).order_by('fecha')
		return queryset

class VacanteCreate(CreateView):
	form_class = VacanteForm
	template_name = 'vacante.html'
	success_url = '/vacantes/'

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.usuario = self.request.user
		return super(VacanteCreate, self).form_valid(form)

class VacanteUpdate(UpdateView):
	model = Vacante
	form_class = VacanteForm
	template_name = 'vacante.html'
	success_url = '/vacantes/'

class VacanteDelete(DeleteView):
	model = Vacante
	success_url = '/vacantes/'

	def dispatch(self, *args, **kwargs):
		resp = super(VacanteDelete, self).dispatch(*args, **kwargs)
		if self.request.is_ajax():
			response_data = {"result": "ok"}
			return JsonResponse(response_data)
		else:
			return resp

vacantes/templates/vacante.html
{% extends 'base.html' %}
{% block contenido %}
<br>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      Formulario de Vacante
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <form id="myform" role="form" method="post" >
        {% csrf_token %}
        <div class="form-group">
          <label>T&iacute;tulo</label>
          {{form.titulo}}
          <p class="help-block">Titulo de la vacante.</p>
        </div>
        <div class="form-group">
          <label>Descripci&oacute;n</label>
          {{form.descripcion}}
          <p class="help-block">Decripci&oacute;n del empleo.</p>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
        <button type="reset" class="btn btn-default">Borrar</button>
        <a href="/vacantes/" class="btn btn-default">Regresar</a>
      </form>
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>
{% endblock %}

vacantes/templates/vacantes.html
{% extends 'base.html' %}
{% block contenido %}
<div class="col-lg-12">
  <h1 class="page-header">Vacantes</h1>
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <a href="/vacante/" class="btn btn-success"> <i class="fa fa-plus"></i> Agregar Vacante</a>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Descripci&oacute;n</th>
            </tr>
          </thead>
          <tbody>
          {% for item in vacantes %}

            <tr>
              <td>{{forloop.counter}}</td>
              <td class="">
                <strong>{{item.titulo}}</strong>
                <small>{{item.fecha|date:'DATETIME_FORMAT'}}</small>
                <p>
                  {{item.descripcion}}
                </p>
                {% if item.solicitud_set.all.count %}
                <a href="{% url 'solicitudes' item.id %}" class="btn btn-info btn-sm"><i class="fa fa-file"></i> Solicitudes {{item.solicitud_set.all.count}}</a>
                {% endif %}
                <a href="{% url 'vacante_edit' item.id %}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i> Editar</a>
                <a  href="{% url 'vacante_delete' item.id %}" data-confirm="true" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"> Eliminar</i></a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>
{% endblock %}