aspirantes/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from usuarios.views import LoginView,LogoutView
from app.views import Home
from personas.views import Personas
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/', TemplateView.as_view(template_name="index.html")),
    url(r'', include('vacantes.urls')),
    url(r'', include('solicitudes.urls')),
    url(r'', include('contratos.urls')),
    url(r'^aspirantes/', Personas.as_view()),
    url(r'^login/$', LoginView.as_view(), name='Login'),
    url(r'^$', Home.as_view()),
    url(r'^salir/$', LogoutView.as_view(),name='Salir'),
    #url(r'^salir/$', 'django.contrib.auth.views.logout',{'next_page': '/login/'},name='Salir'),
    #url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
    #        'document_root': settings.STATIC_ROOT,
    #}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

solicitudes/urls.py
from django.conf.urls import patterns, url
from .views import Solicitudes,SolicitudCreate,SolicitudDelete
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

urlpatterns = [
	url(r'^solicitudes/(?P<pk>\d+)$', login_required(Solicitudes.as_view()), name='solicitudes'),
	url(r'^solicitud/$', SolicitudCreate.as_view(), name='solicitudes'),
	url(r'^confirmacion/$', TemplateView.as_view(template_name="confirmacion.html"), name='confirmacion'),
	#url(r'^solicitud_edit/(?P<pk>\d+)$', login_required(VacanteUpdate.as_view()), name='vacante_edit'),
	url(r'^solicitud_delete/(?P<pk>\d+)$', login_required(SolicitudDelete.as_view()), name='solicitud_delete'),
]

contratos/models.py
from django.db import models
from vacantes.models import Vacante
from solicitudes.models import Solicitud
from django.contrib.auth.models import User
# Create your models here.
class Contrato(models.Model):
    vacante=models.ForeignKey(Vacante)
    solicitud=models.ForeignKey(Solicitud)
    fecha=models.DateTimeField(auto_now_add=True,editable=False)
    usuario=models.ForeignKey('auth.User',editable=False)

    def __unicode__(self):
        return self.vacante.titulo

solicitudes/models.py
from django.db import models
from app.models import Escolaridad
from vacantes.models import Vacante
# Create your models here.
class Solicitud(models.Model):
    correo=models.EmailField()
    nombre=models.CharField(max_length=255)
    direccion=models.TextField()
    telefono=models.CharField(max_length=100)
    ciudad=models.CharField(max_length=100)
    curriculum=models.FileField(upload_to='curriculums')
    fecha=models.DateTimeField(auto_now_add=True,editable=False)
    escolaridad=models.ForeignKey(Escolaridad)
    vacante=models.ForeignKey(Vacante)

    def __unicode__(self):
        return self.correo

solicitudes/forms.py
from django import forms
from .models import Solicitud
from django.forms import Textarea, FileInput
from app.models import Escolaridad
from vacantes.models import Vacante
from contratos.models import Contrato

class SolicitudForm(forms.ModelForm):
    class Meta:
        model = Solicitud
        fields = "__all__"
        widgets={
            "correo":forms.TextInput(attrs={'required':'True','placeholder':'Correo Electronico','class':'form-control'}),
            "nombre":forms.TextInput(attrs={'required':'True','placeholder':'Nombre Completo','class':'form-control'}),
            "direccion":forms.TextInput(attrs={'required':'True','placeholder':'Direccion','class':'form-control'}),
            "ciudad":forms.TextInput(attrs={'required':'True','placeholder':'Ciudad','class':'form-control'}),
            "telefono":forms.TextInput(attrs={'required':'True','placeholder':'Telefono(s)','class':'form-control'}),
            "curriculum":forms.FileInput(attrs={'required':'True'}),
            "escolaridad":forms.Select(attrs={'class':'form-control'}),
            "vacante":forms.Select(attrs={'class':'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(SolicitudForm, self).__init__(*args, **kwargs)
        self.fields['escolaridad'].empty_label = None
        self.fields['escolaridad'].queryset = Escolaridad.objects.order_by('id')
        self.fields['vacante'].empty_label = None
        contratos=Contrato.objects.all()
        self.fields['vacante'].queryset = Vacante.objects.exclude(contrato__in=contratos).order_by('id')

solicitudes/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView,DeleteView
from django.views.generic import ListView
from .forms import SolicitudForm
from .models import Solicitud
from vacantes.models import Vacante
from django.http import JsonResponse

# Create your views here.

class Solicitudes(ListView):
	template_name = "solicitudes.html"
	model = Solicitud
	context_object_name = "solicitudes"

	def dispatch(self, *args, **kwargs):
		return super(Solicitudes, self).dispatch(*args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(Solicitudes, self).get_context_data(**kwargs)
		vacante=Vacante.objects.get(pk=self.kwargs['pk'])
		context['titulo']=vacante.titulo
		return context

	def get_queryset(self):
		queryset=super(Solicitudes,self).get_queryset().filter(vacante=self.kwargs['pk']).order_by('fecha')
		return queryset


class SolicitudCreate(CreateView):
	form_class = SolicitudForm
	template_name = 'solicitud.html'
	success_url = '/confirmacion/'

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.usuario = self.request.user
		return super(SolicitudCreate, self).form_valid(form)

class SolicitudDelete(DeleteView):
	model = Solicitud
	success_url = '/'

	def dispatch(self, *args, **kwargs):
		resp = super(SolicitudDelete, self).dispatch(*args, **kwargs)
		if self.request.is_ajax():
			response_data = {"result": "ok"}
			return JsonResponse(response_data)
		else:
			return resp

solicitudes/templates/confirmacion.html
{% load static from staticfiles %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Formulario de Solicitud</title>
  <link rel="stylesheet" href="css/normalize.css">
  <link href='http://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static "css/frmcss.css" %}">
</head>
<body>
<form action="">
<h1>Gracias por tu Solicitud</h1>
<fieldset>
<p>En breve recibiras un correo de confirmacion, revisaremos tu curriculum y se te enviara un correo en caso de ser seleccionado.</p>
</fieldset>
<fieldset>
  <a href="/solicitud/" class="boton">Regresar</a>
</fieldset>


</form>
</body>
</html>

solicitudes/templates/solicitud.html
{% load static from staticfiles %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Formulario de Solicitud</title>
  <link rel="stylesheet" href="css/normalize.css">
  <link href='http://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static "css/frmcss.css" %}">
</head>
<body>

  <form role="form" method="post" enctype="multipart/form-data" >
    <h1>Formulario de Solicitud</h1>
    {% csrf_token %}
    <fieldset>
      <legend><span class="number">1</span>Seleccione una Vacante</legend>
      {{form.vacante}}
    </fieldset>
    <fieldset>
      <legend><span class="number">2</span>Datos de Contacto</legend>
      {{form.correo}}
      {{form.nombre}}
      {{form.direccion}}
      {{form.ciudad}}
      {{form.telefono}}
    </fieldset>
    <fieldset>
      <legend><span class="number">3</span>Escolaridad</legend>
      {{form.escolaridad}}
    </fieldset>
    <fieldset>
      <legend><span class="number">4</span>Anexar Curriculum</legend>
      {{form.curriculum}}
    </fieldset>
    <br>
    <br>
    <button type="submit" onclick="return confirm('Los datos son correctos?')">Enviar Solicitud</button>
    <button type="reset">Borrar</button>
  </form>


</body>
</html>

solicitudes/templates/solicitudes.html
{% extends 'base.html' %}
{% block contenido %}
<div class="col-lg-12">
  <h1 class="page-header">{{titulo}}</h1>
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      Lista de Solicitudes
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">

      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>#</th>
              <th>Vacante</th>
              <th>Nombre</th>
              <th>Fecha</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          {% for item in solicitudes %}
            <tr data-toggle="collapse" data-parent="#accordion" href="#collapseOne{{forloop.counter}}" aria-expanded="false" class="collapsed">
              <td>{{forloop.counter}}</td>
              <td>
                {{item.vacante}}
              </td>
              <td>{{item.nombre}}</td>
              <td>{{item.fecha|date:'d-m-Y H:i'}}</td>
              <td>
              </td>
            </tr>
            <tr>
              <td style="padding: 0px;" colspan="5">
                <div id="collapseOne{{forloop.counter}}" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                  <div class="panel-body">
                    <div>
                      <address>
                        <strong>Vacante</strong>
                        <br>{{item.vacante}}
                        <br><strong>Descripcion</strong>
                        <br>{{item.vacante.descripcion}}
                      </address>
                      <address>
                        <strong>Correo: </strong>{{item.correo}}
                        <br><strong>Nombre: </strong>{{item.nombre}}
                        <br><strong>Direccion: </strong>{{item.direccion}}
                        <br><strong>Tel: </strong>{{item.telefono}}
                        <br><strong>Escolaridad: </strong>{{item.escolaridad}}
                      </address>
                      <address>
                        <strong><a href="{{item.curriculum.url}}">Ver Curriculum</a></strong>
                        <br>
                      </address>

                    </div>
                    <div>
                      <form action="/contrato/" method="post">
                        {% csrf_token %}
                        <input type="hidden" id="id_vacante" name="id_vacante" value="{{item.vacante.id}}">
                        <input type="hidden" id="id_solicitud" name="id_solicitud" value="{{item.id}}">
                        <input type="submit" class="btn btn-primary" onclick="return confirm('Esta seguro?')" value="Contratar">
                        <a  href="{% url 'solicitud_delete' item.id %}" data-confirm="true" class="btn btn-danger">Denegar</a>
                      </form>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>
{% endblock %}